# Generated by Django 4.1.13 on 2024-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_category_subcategory_and_more'),
        ('orders', '0002_remove_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orders.OrderItem', to='products.product'),
        ),
    ]
